### ISSUE TITLE
django.db.utils.IntegrityError: insert or update on table "drf_stripe_subscriptionitem" violates foreign key constraint "drf_stripe_subscript_price_id_56df13e9_fk_drf_strip"

### ISSUE THREAD

**Issue by janbaykara** [oscarychen/drf-stripe-subscription#17]
Caused by `python manage.py update_stripe_subscriptions`

```
$ python manage.py update_stripe_subscriptions
message='Request to Stripe api' method=get path=https://api.stripe.com/v1/subscriptions?limit=100
message='Stripe API response' path=https://api.stripe.com/v1/subscriptions?limit=100 response_code=200
Updated subscription sub_JqlXq6MuRv2zKF
Updated sub item si_JqlXL5vg7czvwV
...
[more lines like this]
...
Created 34 new Subscriptions.
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 267, in _commit
    return self.connection.commit()
psycopg2.errors.ForeignKeyViolation: insert or update on table "drf_stripe_subscriptionitem" violates foreign key constraint "drf_stripe_subscript_price_id_56df13e9_fk_drf_strip"
DETAIL:  Key (price_id)=(both_regular_monthly_EU) is not present in table "drf_stripe_price".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vscode/.local/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/home/vscode/.local/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vscode/.local/lib/python3.9/site-packages/django/core/management/base.py", line 414, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/vscode/.local/lib/python3.9/site-packages/django/core/management/base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "/home/vscode/.local/lib/python3.9/site-packages/drf_stripe/management/commands/update_stripe_subscriptions.py", line 14, in handle
    stripe_api_update_subscriptions(limit=kwargs.get('limit'), starting_after=kwargs.get('starting_after'))
  File "/usr/local/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/vscode/.local/lib/python3.9/site-packages/django/db/transaction.py", line 255, in __exit__
    connection.commit()
  File "/home/vscode/.local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/home/vscode/.local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 291, in commit
    self._commit()
  File "/home/vscode/.local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 267, in _commit
    return self.connection.commit()
  File "/home/vscode/.local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/vscode/.local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 267, in _commit
    return self.connection.commit()
django.db.utils.IntegrityError: insert or update on table "drf_stripe_subscriptionitem" violates foreign key constraint "drf_stripe_subscript_price_id_56df13e9_fk_drf_strip"
DETAIL:  Key (price_id)=(both_regular_monthly_EU) is not present in table "drf_stripe_price".
```

**Comment by oscarychen** [comment]
Did you pull in your stripe data first? Such as prices and products?
