### ISSUE TITLE
ModuleNotFoundError: No module named 'pydantic'

### ISSUE THREAD

**Issue by piotrsynowiec** [oscarychen/drf-stripe-subscription#28]
Hi, thank you for your work on this package.

I installed the package as recommended in the documentation and stumbled upon the problem:

```
Traceback (most recent call last):
  File "/code/manage.py", line 21, in <module>
    main()
  File "/code/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 420, in execute
    django.setup()
  File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 304, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/site-packages/drf_stripe/models.py", line 4, in <module>
    from .stripe_models.subscription import ACCESS_GRANTING_STATUSES
  File "/usr/local/lib/python3.9/site-packages/drf_stripe/stripe_models/subscription.py", line 5, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
```

The 'pydantic' module doesn't seem to be included in the required packages.

**Comment by oscarychen** [comment]
@piotrsynowiec thanks for catching this. I'll update the required dependencies in the next build. For now you could manually install the missing module in your project.

**Comment by BuddhiAbeyratneAL** [comment]
We have a few more issues 
Like stripe not installing via poetry and a bunch of missing migrations @oscarychen

**Comment by BuddhiAbeyratneAL** [comment]
@oscarychen what's the PR and contribution processes like

**Comment by oscarychen** [comment]
@BuddhiAbeyratneAL I've not used poetry, if you make a PR ill review it.
